export const mockproducts = [
  {
    id: 'prod_kpnNwADxLzlmXB',
    created: 1707974547,
    updated: 1708163913,
    active: true,
    permalink: 'UxeBoj',
    name: 'Apple MacBook Air',
    description:
      '<p></p><ul><li><p>All-Day Battery Life – Go longer than ever with up to 18 hours of battery life.</p></li><li><p>Powerful Performance – Take on everything from professional-quality editing to action-packed gaming with ease. The Apple M1 chip with an 8-core CPU delivers up to 3.5x faster performance than the previous generation while using way less power.</p></li><li><p>Superfast Memory – 8GB of unified memory makes your entire system speedy and responsive. That way it can support tasks like memory-hogging multitab browsing and opening a huge graphic file quickly and easily.</p></li><li><p>Stunning Display – With a 13.3-inch/33.74 cm Retina display, images come alive with new levels of realism. Text is sharp and clear, and colors are more vibrant.</p></li><li><p>Why Mac – Easy to learn. Easy to set up. Astoundingly powerful. Intuitive. Packed with apps to use right out of the box. Mac is designed to let you work, play, and create like never before.</p></li></ul>',
    price: {
      raw: 1011,
      formatted: '1,011.00',
      formatted_with_symbol: '$1,011.00',
      formatted_with_code: '1,011.00 USD',
    },
    inventory: {
      managed: true,
      available: 50,
    },
    sku: null,
    sort_order: 0,
    seo: {
      title: null,
      description: null,
    },
    thank_you_url: null,
    meta: null,
    conditionals: {
      is_active: true,
      is_tax_exempt: false,
      is_pay_what_you_want: false,
      is_inventory_managed: true,
      is_sold_out: false,
      has_digital_delivery: false,
      has_physical_delivery: true,
      has_images: true,
      collects_fullname: false,
      collects_shipping_address: true,
      collects_billing_address: false,
      collects_extra_fields: false,
    },
    is: {
      active: true,
      tax_exempt: false,
      pay_what_you_want: false,
      inventory_managed: true,
      sold_out: false,
    },
    has: {
      digital_delivery: false,
      physical_delivery: true,
      images: true,
    },
    collects: {
      fullname: false,
      shipping_address: true,
      billing_address: false,
      extra_fields: false,
    },
    checkout_url: {
      checkout: 'https://checkout.chec.io/UxeBoj?checkout=true',
      display: 'https://checkout.chec.io/UxeBoj',
    },
    categories: [],
    image: {
      id: 'ast_gvRjwObO3ml4mN',
      url: 'https://cdn.chec.io/merchants/56103/assets/6uEp0drDg6pAUn5h|macbook.jpg',
      description: null,
      is_image: true,
      filename: 'macbook.jpg',
      file_size: 40326,
      file_extension: 'jpg',
      image_dimensions: {
        width: 1500,
        height: 1500,
      },
      meta: [],
      created_at: 1708147007,
      updated_at: 1708147010,
    },
  },
];
